# Copyright 2010 Petar Maymounkov. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=github.com/kelleysoft/Lispish/stutter

GOFILES=\
	stutter.go\
	context.go\
	builtins.go\
	rep.go\

include $(GOROOT)/src/Make.pkg
